version: '3.9'
services:
    go-dev:
        container_name: jury-dev-backend
        environment:
            - MONGODB_URI=${MONGODB_URI}
            - JURY_ADMIN_PASSWORD=${JURY_ADMIN_PASSWORD}
            - EMAIL_HOST=${EMAIL_HOST}
            - EMAIL_PORT=${EMAIL_PORT}
            - EMAIL_FROM=${EMAIL_FROM}
            - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
            - EMAIL_USERNAME=${EMAIL_USERNAME}
            - EMAIL_PASSWORD=${EMAIL_PASSWORD}
            - SENDGRID_API_KEY=${SENDGRID_API_KEY}
            - VITE_JURY_NAME=${JURY_NAME}
            - PORT=3301
            - KEYCLOAK_OAUTH2_CLIENT_ID=${KEYCLOAK_OAUTH2_CLIENT_ID}
            - KEYCLOAK_OAUTH2_CLIENT_SECRET=${KEYCLOAK_OAUTH2_CLIENT_SECRET}
            - ORIGIN=${ORIGIN:?}
            - API_ORIGIN=${API_ORIGIN:?}
        build:
            context: './'
            dockerfile: dev.Dockerfile
        ports:
            - ${PORT:-3301}:3301
        volumes:
            - ./server:/jury

    node-dev:
        depends_on:
            - 'go-dev'
        container_name: jury-dev-frontend
        environment:
            - VITE_JURY_NAME=${JURY_NAME}
            - VITE_JURY_URL=${API_ORIGIN}/api
        build:
            context: './'
            dockerfile: client/dev.Dockerfile
        ports:
            - "3300:3300"
        volumes:
            - ./client:/client
