services:
    go-dev:
        container_name: jury-dev-backend
        environment:
            - GIN_MODE=${GIN_MODE}

            - VITE_JURY_NAME=${JURY_NAME}
            - JURY_ADMIN_PASSWORD=${JURY_ADMIN_PASSWORD}

            - ORIGIN=${ORIGIN:?}
            - API_ORIGIN=${API_ORIGIN:?}

            - KEYCLOAK_REALM=${KEYCLOAK_REALM}
            - KEYCLOAK_BASE_URL=${KEYCLOAK_BASE_URL}
            - KEYCLOAK_ADMIN_BASE_URL=${KEYCLOAK_ADMIN_BASE_URL}

            - KEYCLOAK_OAUTH2_CLIENT_ID=${KEYCLOAK_OAUTH2_CLIENT_ID}
            - KEYCLOAK_OAUTH2_CLIENT_SECRET=${KEYCLOAK_OAUTH2_CLIENT_SECRET}

            - MONGODB_URI=${MONGODB_URI}
            - DATABASE_NAME=${DATABASE_NAME}

            - EMAIL_HOST=${EMAIL_HOST}
            - EMAIL_PORT=${EMAIL_PORT}
            - EMAIL_FROM=${EMAIL_FROM}
            - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
            - EMAIL_USERNAME=${EMAIL_USERNAME}
            - EMAIL_PASSWORD=${EMAIL_PASSWORD}
            - SENDGRID_API_KEY=${SENDGRID_API_KEY}

            - PORT=${API_PORT:-3301}
        build:
            context: './'
            dockerfile: dev.Dockerfile
        ports:
            - ${PORT:-3301}:3301
        volumes:
            - ./server:/jury

    node-dev:
        depends_on:
            - 'go-dev'
        container_name: jury-dev-frontend
        environment:
            - VITE_JURY_NAME=${JURY_NAME}
            - VITE_API_ORIGIN=${API_ORIGIN}
        build:
            context: './'
            dockerfile: client/dev.Dockerfile
        ports:
            - "3300:3300"
        volumes:
            - ./client:/client
